/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Chandra
 */
public class MenuPaket extends javax.swing.JFrame {

    /**
     * Creates new form MenuPaket
     */
    public MenuPaket() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        paketDButton = new javax.swing.JButton();
        paketAButton = new javax.swing.JButton();
        paketBButton = new javax.swing.JButton();
        paketCButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(338, 450));

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ICON/icons8-a-64.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 120, 70, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ICON/icons8-b-64.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 120, 70, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ICON/icons8-c-64.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 250, 70, 64);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ICON/icons8-d-64.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 260, 70, 64);

        paketDButton.setBackground(new java.awt.Color(137, 135, 191));
        paketDButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        paketDButton.setText("PAKET D");
        paketDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketDButtonActionPerformed(evt);
            }
        });
        jPanel1.add(paketDButton);
        paketDButton.setBounds(180, 320, 80, 23);

        paketAButton.setBackground(new java.awt.Color(137, 135, 191));
        paketAButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        paketAButton.setText("PAKET A");
        paketAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketAButtonActionPerformed(evt);
            }
        });
        jPanel1.add(paketAButton);
        paketAButton.setBounds(60, 190, 90, 23);

        paketBButton.setBackground(new java.awt.Color(137, 135, 191));
        paketBButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        paketBButton.setText("PAKET B");
        paketBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketBButtonActionPerformed(evt);
            }
        });
        jPanel1.add(paketBButton);
        paketBButton.setBounds(170, 190, 90, 23);

        paketCButton.setBackground(new java.awt.Color(137, 135, 191));
        paketCButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        paketCButton.setText("PAKET C");
        paketCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketCButtonActionPerformed(evt);
            }
        });
        jPanel1.add(paketCButton);
        paketCButton.setBounds(60, 320, 90, 23);

        jLabel6.setFont(new java.awt.Font("Freestyle Script", 3, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ICON/icons8-wedding-50.png"))); // NOI18N
        jLabel6.setText("THINGKER");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 400, 160, 50);

        min.setFont(new java.awt.Font("Thames", 1, 35)); // NOI18N
        min.setText("-");
        min.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel1.add(min);
        min.setBounds(232, 10, 30, 30);

        exit.setFont(new java.awt.Font("Thames", 1, 35)); // NOI18N
        exit.setText("x");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(260, 10, 30, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/ICON/icons8-back-to-30.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(20, 20, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Background/menu (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paketBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketBButtonActionPerformed
        // TODO add your handling code here:
        PaketB b = new PaketB();
        b.setVisible(true);
        b.pack();
        b.setLocationRelativeTo(null);
        b.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_paketBButtonActionPerformed

    private void paketAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketAButtonActionPerformed
        // TODO add your handling code here:
        PaketA a = new PaketA();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_paketAButtonActionPerformed

    private void paketCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketCButtonActionPerformed
        // TODO add your handling code here:
        PaketC c = new PaketC();
        c.setVisible(true);
        c.pack();
        c.setLocationRelativeTo(null);
        c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_paketCButtonActionPerformed

    private void paketDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketDButtonActionPerformed
        // TODO add your handling code here:
        PaketD d = new PaketD();
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_paketDButtonActionPerformed

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        Searching src = new Searching();
        src.setVisible(true);
        src.pack();
        src.setLocationRelativeTo(null);
        src.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel min;
    private javax.swing.JButton paketAButton;
    private javax.swing.JButton paketBButton;
    private javax.swing.JButton paketCButton;
    private javax.swing.JButton paketDButton;
    // End of variables declaration//GEN-END:variables
}
